### ISSUE TITLE
Crash on trying to add watch to directory or file without read permission

### ISSUE THREAD

**Issue by thindil** [onox/inotify-ada#1]
If the user try to add watch (in recursive instance) to a directory which contains files or other directories to which the user don't have read permission ends with raised ADA.IO_EXCEPTIONS.USE_ERROR.
Steps to reproduce:
1. Build examples
2. Run it to monitor root directory:
`bin/monitor /`
3. The program crash with 
`raised ADA.IO_EXCEPTIONS.USE_ERROR : unreadable directory "root"`

Probably Ada.Directories.Search causes this problem (inotify-recursive.adb line 52). On Linux the program don't need read permission to read file/directory name (let's say it is problem in the Ada specification). I think that better option is to use Read from GNAT.Directory_Operations. At least it should not crash :)

**Comment by onox** [comment]
> On Linux the program don't need read permission to read file/directory name

`Ada.Directories.Search` is used to scan for folders *inside* the folder that you are trying to watch. If the folder is owned by a different user and has 700 permissions, then the current user cannot see what's inside it.

I will try to change the behavior so that it only raises Use_Error for folders that are watched manually, but not for those that are added recursively.
